# Generated by Django 3.1.1 on 2020-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Vendor', 'Vendor')], max_length=250),
        ),
    ]
