# Generated by Django 3.1.1 on 2020-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200920_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('Company Manager', 'Company Manager'), ('Vendor', 'Vendor')], max_length=250),
        ),
    ]
