# Generated by Django 3.0.6 on 2020-09-19 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_manager',
            new_name='CompanyManager',
        ),
        migrations.RenameModel(
            old_name='Company_order',
            new_name='CompanyOrder',
        ),
        migrations.RenameModel(
            old_name='Vendor_order',
            new_name='VendorOrder',
        ),
    ]
