# Generated by Django 3.1.1 on 2020-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorder',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
